### ISSUE TITLE
internal/modules/cjs/loader.js:583     throw err;     ^

### ISSUE THREAD

**Issue by wallisonalves** [compalmanel/WavesLPoSTools#1]
~/WavesLPoSTools$ node checkTransfer.js
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/home/myhome/WavesLPoSTools/checkTransfer.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:752:3)
myhome@waves:~/WavesLPoSTools$

**Comment by wallisonalves** [comment]
What is causing this error?

**Comment by compalmanel** [comment]
This error is displayed if the necessary npm modules are not installed.

Please make sure the installations instructions have been executed.
